### ISSUE TITLE
add more info on each of the dataset level gantt chart to orient the context

### ISSUE THREAD

**Issue by yuliujpl** [Labcas-NIST/Labcas-ui#100]

**Comment by yuliujpl** [comment]
@hoodriverheather  here are all the values that could show in a virtual dataset in order to provide users more context to which virtual hierarchy they've drilled into:
 "virtual_hierarchy_dataset_displayfields":"DatasetDescription,WorkingGroupDesignation,PoCName*,InstitutionName*,Institution,LeadPoC,LeadPoCEmail,OwnerPrincipal,Organism,ProtocolHandle,SourceID,ParentCellLine,MammalianCellCode,InstrumentHandle,ExpansionType,StudyID,StudyType,Discipline,PublicInstitutionName,DataCustodian,DataCustodianName,DataCustodianEmail,BlindedDataset,MaterialType,AssayType"

Essentially if all files share the same values for these headers, these will show at the virtual dataset level!

**Comment by hoodriverheather** [comment]
@yuliujpl I missed the call where this was discussed. What happened to the list defined by Sierra and then you click view more to see the rest? I think I'm losing it :)

**Comment by yuliujpl** [comment]
@hoodriverheather it's the same list but with additional fields from other collections! Since fieldnames differ at the file level between collections, I have to add some additional fields in order for virtual dataset details in other collections to be more "filled out". Do you want me to remove the fields for the other collections and only use Sierra's?

**Comment by hoodriverheather** [comment]
@yuliujpl I think this is good for now. I can see some metadata for the virtual dataset and we can always modify if John wants to add more.
