### ISSUE TITLE
Genome Editing multi-qc icon shows no file found

### ISSUE THREAD

**Issue by yuliujpl** [Labcas-NIST/Labcas-ui#101]
The first file listed in the collection view of the hierarchy. When i click on the image icon, i get file not found. the image icon for the one below works.

![Image](https://user-images.githubusercontent.com/58526347/259264800-723f8a8b-af9d-403d-8a3d-7fc70942fac5.png)

![Image](https://user-images.githubusercontent.com/58526347/259264816-f69323b6-defc-4543-a560-05638121d2a7.png)

**Comment by yuliujpl** [comment]
Fixed only in prod, too much data to transfer to dev!

**Comment by hoodriverheather** [comment]
👍
