### ISSUE TITLE
bring back memory feature to keep virtual dataset uncollapsed and scroll down feature

### ISSUE THREAD

**Issue by yuliujpl** [Labcas-NIST/Labcas-ui#108]

**Comment by hoodriverheather** [comment]
@yuliujpl This works great when, from the collection, you click on a dataset (down the virtual view list). Then click on the collection name in the breadcrumbs.

It doesn't seem to work. I think it's when I use the browsers back button. Is that how it always was?

**Comment by hoodriverheather** [comment]
@yuliujpl It still intermittently not working with back button on brower.

**Comment by yuliujpl** [comment]
should work with back button now!

**Comment by hoodriverheather** [comment]
@yuliujpl it's still not working for me. 
To reproduce: 

1. open flow cyt collection
2. click expand all check box
3. expand collection
4. scroll way down and select a virtual dataset that will show files (lowest level)
5. then click the back button
6. it takes me back to the top of the virtual view
7. :(

**Comment by yuliujpl** [comment]
@hoodriverheather prod has been updated, can you try to see if the memory feature now works for prod?

**Comment by hoodriverheather** [comment]
@yuliujpl it works perfect! thanks!
