### ISSUE TITLE
If there's no images selected, setup a warning to prevent image viewing.

### ISSUE THREAD

**Issue by hoodriverheather** [Labcas-NIST/Labcas-ui#111]

**Comment by hoodriverheather** [comment]
@yuliujpl I'm confused on how to test this, can you provide more details?

I see the View Cytometry Files button - currently this is showing for all collections, not just Flow Cytometry. 
When I click on this button it opens the BCyto, even if there's no file selected.

**Comment by yuliujpl** [comment]
@hoodriverheather this is done for the cart image button! Also view flow is removed in production!

**Comment by hoodriverheather** [comment]
@yuliujpl Awesome! thanks!
