### ISSUE TITLE
Cell line dataset virtual view Event Date needs to be formatted?

### ISSUE THREAD

**Issue by yuliujpl** [Labcas-NIST/Labcas-ui#113]
The virtual view Event date seems wrong or not formatted? (see below)

![Image](https://user-images.githubusercontent.com/58526347/266433420-6412d945-4ed9-4dfb-9841-d9b75f37c3b6.png)

**Comment by yuliujpl** [comment]
Only done in the virtual hierarchy view!

**Comment by hoodriverheather** [comment]
@yuliujpl Looks great!
