### ISSUE TITLE
Download metadata no longer available at virtual dataset level

### ISSUE THREAD

**Issue by hoodriverheather** [Labcas-NIST/Labcas-ui#117]
![Image](https://github.com/Labcas-NIST/Labcas-ui/assets/58526347/86311b94-d29a-4aee-a9db-048d9f9f757c)

I'm pretty sure there used to be a download metadata icon at the virtual view dataset level, so that users can download all the metadata in a single file that is related to the entire set they are working with. Did we decide to remove? Sorry, I don't remember.

**Comment by yuliujpl** [comment]
@hoodriverheather  I do have metadata in the following two sections, but do not see any code for the collection level! Currently, even in the virtual dataset level, there's no way to select all files under a dataset, you have to manually select files in a dataset, and then you can click on download metadata. So there's no full dataset metadata download, is this something that we should implement?


![Image](https://github.com/Labcas-NIST/Labcas-ui/assets/15621084/2aa8e8af-7131-4fd2-8e8c-fe42be7aa358)

**Comment by hoodriverheather** [comment]
@yuliujpl this would be a great thing to ask NIST. I'm not sure how they envision people downloading the data with the metadata. Flow and Genome Editing will both have ideas.
