### ISSUE TITLE
add search to nist labcas

### ISSUE THREAD

**Issue by yuliujpl** [Labcas-NIST/Labcas-ui#130]

**Comment by yuliujpl** [comment]
@hoodriverheather  please feel free to try nist labcas search in the staging version! Currently facets are pointing to collection level which only shows 1. Would be great to know if your specific search use cases work or not!

**Comment by hoodriverheather** [comment]
@yuliujpl This is great! I entered in some of the metadata for the files John asked us to remove and it seems to work great. 
For example, "AZSFPI" is the PrincipalContact for the files John wanted deleted. you can search and none appear. You can also search for a file name that's been deleted and it doesn't appear "FCSC_WG2-001_AZSSF_Aurora_APC-Cy7-cryoPBMC_SOP-02_e1_ 1_ 1_ 1_FCS.fcs".

Just to show it's working - It does find this one "AZGBBIO". And this file "FCSC_WG2-001_AZGBBIO_SymphonyA5_AqBead_SOP-02_e4_1_1_1_FCS.fcs"

Did you want to respond back to John's email to let him know you cleaned up his files?

Thanks!
Heather

**Comment by hoodriverheather** [comment]
Works great! Excited to get some feedback from NIST on the facets they want shown :)
