### ISSUE TITLE
John's updated files

### ISSUE THREAD

**Issue by yuliujpl** [Labcas-NIST/Labcas-ui#132]
You should be able to download 60 FCS files with “Q2LabSol_Aurora-2” in the name.  Please replace the existing “Q2LabSol_Aurora-2” FCS files in LabCAS with these files (they have the same names).  The metadata tables do not change.

This is left over from the problem that a company had two flow cytometers of the same name and it messed up our conversions.  Ideally this should fix it.

**Comment by hoodriverheather** [comment]
@yuliujpl Looks great!
