### ISSUE TITLE
metadata schema viewer at collection level

### ISSUE THREAD

**Issue by yuliujpl** [Labcas-NIST/Labcas-ui#134]

**Comment by yuliujpl** [comment]
get rough draft generated before wed for iteration.

**Comment by yuliujpl** [comment]
@hoodriverheather  at the bottom of each collection page in test. However, I made some tabs automatically available for all the collections and some collection specifc. Here is the mapping, can you please confirm what mappings you want to change it to? Also, I know there's some sorting issues where there's empty rows and rows may not be in order, I can certainly fix those!

Key is the collection_id, value is the list of sheet names pulled from your google sheet we want to display per collection.
{
     "Microbial": ["Readme","Core Collection-V 1.0","Core File V 1.0","CoreILSExtension","CoreMicrobial V 1.0", "CFU V 1.0", "ImpedanceFC V 1.0", "FluorescenceFC V 1.0","SharedMetadata","Structure"],
     "Cell_Line_Provenance": ["Readme","Core Collection-V 1.0","Core File V 1.0","CoreILSExtension","CellLineExpansionExtension DRAFT", "TelemetryExtension DRAFT","SharedMetadata","Structure"],
     "Genome_Editing_Consortium": ["Readme","Core Collection-V 1.0","Core File V 1.0","CoreILSExtension","GenomicSequencingExtension","GenomicsBioinformaticsExtension","BionanoExtension","SharedMetadata","Structure"],
     "NIST_Flow_Cytometry_Standards_Consortium": ["Readme","Core Collection-V 1.0","Core File V 1.0","CoreILSExtension","FlowCytometryExtension DRAFT","SharedMetadata","Structure"]
  }

**Comment by hoodriverheather** [comment]
@yuliujpl this is a good start. 
You can remove from all collections the following tabs: 

- Readme 
- Shared metadata
- Structure

For Microbial you can also remove the CoreILSExtension
Genome_Editing looks good.
Flow Cytometry remove CoreILSExtension
Cell_Line - i would hold off on anything for now. It's all very draft or metadata i made up :)

I also am having a difficult time scrolling through the "sheets".

It would be great to show the required fields at the top.

When you demo, can you mention that some of these are more draft than others. Thanks!

**Comment by yuliujpl** [comment]
Sounds great!
________________________________
From: hoodriverheather ***@***.***>
Sent: Tuesday, May 14, 2024 5:20 PM
To: Labcas-NIST/Labcas-ui ***@***.***>
Cc: Liu, David (US 3902-Affiliate) ***@***.***>; Mention ***@***.***>
Subject: [EXTERNAL] Re: [Labcas-NIST/Labcas-ui] metadata schema viewer at collection level (Issue #134)


@yuliujpl<https://urldefense.us/v3/__https://github.com/yuliujpl__;!!PvBDto6Hs4WbVuu7!PyN6P9KwtjZ0kzAqXZbv5oue3frCeoKtiz-W_1InHpSseUWw2pT_Wy36_USD159L2xGaBjHd_8HrQCyDD9lcvpNiI8IVhA$> this is a good start.
You can remove from all collections the following tabs:

  *   Readme
  *   Shared metadata
  *   Structure

For Microbial you can also remove the CoreILSExtension
Genome_Editing looks good.
Flow Cytometry remove CoreILSExtension
Cell_Line - i would hold off on anything for now. It's all very draft or metadata i made up :)

I also am having a difficult time scrolling through the "sheets".

It would be great to show the required fields at the top.

When you demo, can you mention that some of these are more draft than others. Thanks!
