### ISSUE TITLE
John new script changes

### ISSUE THREAD

**Issue by yuliujpl** [Labcas-NIST/Labcas-ui#142]
Sorry for delay.  I ran the snapshot script.  Worked mostly, but I am missing about 1000 files.  Not sure how many are real files.  I do know that we need to change the “save” directory structure because it causes download errors due to length.  Here are my suggestions.

 

Set the local directory structure to ./FCSC_WG1-001/filename for the WG1 FCS and accessory files and ./FCSC_WG2-001 for the WG2 FCS and accessory files. 
When the file is downloading, please provide specifications indicating “downloaded 500 out of 5000 files” after each file download is complete.
Need instructions on how to stop the script (do I just close the window?)
 

 

Also, wanted to ask how difficult it will be to add another column to our facet metadata table.  We are going to need a column named “complete” for each row.  We are finding some of the datasets in the JPL collection are missing a few files.  We will probably mark those as incomplete after we complete a little more analysis.

**Comment by hoodriverheather** [comment]
@yuliujpl Can you add a cancel button to the download? This would also be useful in EDRN, as there's no way to cancel out prior to downloading or during download.
