### ISSUE TITLE
Data Update: New Genome Datasets curated by Lisa need to be loaded into LabCAS

### ISSUE THREAD

**Issue by yuliujpl** [Labcas-NIST/Labcas-ui#44]
From Sierra:
Start Participant I

Lisa:
I have updated our GitHub with several more datasets for the Genome Editing group. It is up to date with what is available on Globus, with the exception of one dataset, “Participant D”. This one has metadata that doesn’t follow our typical upload sheet. We can tag up on this quickly next week so you can explain to me what the best way for me to prepare this would be. The other ones that are ready are:
Participant C Hybrid
Participant C Archer
COBO
Participant I

**Comment by hoodriverheather** [comment]
moved to private repo.
