### ISSUE TITLE
Cleanup any EDRN references, links, etc.

### ISSUE THREAD

**Issue by hoodriverheather** [Labcas-NIST/Labcas-ui#53]
https://labcas.jpl.nasa.gov/nist/c/index.html?collection_id=NIST_Flow_Cytometry_Standards_Consortium
The Institution: National Institutes of Standards and Technology on this page takes you to EDRN Portal. See screenshot.

![Image](https://user-images.githubusercontent.com/58526347/232633939-cb7a208b-c286-42fc-ba72-bd73ee2fc7b8.png)

https://labcas.jpl.nasa.gov/nist/c/index.html?collection_id=Genome_Editing_Consortium
Same issue for the Genome Editing Collection. See screenshot.

![Image](https://user-images.githubusercontent.com/58526347/232634141-7e594fb7-8958-4620-b545-1503668899b2.png)

These will need to link to KSDB pop-ups. Need further design in KSDB issue #24

**Comment by yuliujpl** [comment]
Temporarily it points to nist.gov!

**Comment by hoodriverheather** [comment]
@yuliujpl would it be possible for the Genome Ediitng to point to - https://www.nist.gov/programs-projects/nist-genome-editing-consortium
and the Flow Cytometry to point to - https://www.nist.gov/programs-projects/nist-flow-cytometry-standards-consortium

and the Cell Line to point to - https://www.nist.gov/mml/bbd

Or they could all point to https://www.nist.gov/mml/bbd for now?

**Comment by yuliujpl** [comment]
just to move quickly before I go, I changed it to https://www.nist.gov/mml/bbd for now!

**Comment by hoodriverheather** [comment]
Great!
