### ISSUE TITLE
Swagger documentation for Labcas API for users to do custom downloads

### ISSUE THREAD

**Issue by hoodriverheather** [Labcas-NIST/Labcas-ui#56]

**Comment by hoodriverheather** [comment]
I met with Sean and he is creating documentation for all LabCAS APIs.

**Comment by yuliujpl** [comment]
Okay, so I'll wait for him to finish and add it to NIST labcas?

**Comment by hoodriverheather** [comment]
@yuliujpl this is finished and now currently posted to the Portal at https://edrn-dev.jpl.nasa.gov/portal/renaissance/data-and-resources/cde/labcas-metadata-and-common-data-elements/labcas-api/
Ready to be posted to NIST LabCAS :)
