### ISSUE TITLE
Rename datasets

### ISSUE THREAD

**Issue by hoodriverheather** [Labcas-NIST/Labcas-ui#70]
From Sierra's Google Doc - https://docs.google.com/document/d/15oX1Jrv1qMaGykHHpoOcqwXqOoDzSqsrjbsaYhjQSuc/edit

Edit the dataset names for the placeholder datasets under Unblinded (Bionano Genomics and TwinStrand Biosciences). For now if we have the names with (pending).

Replace the Bionano Genomics and TwinStrandbiosciences with Mission Bio (pending) and 

![Image](https://user-images.githubusercontent.com/58526347/246542920-caedf6f4-cfaf-4723-ac69-ebba26da7361.png)

Illumina (pending)

**Comment by hoodriverheather** [comment]
@yuliujpl I'm not seeing any renamed datasets. 


![Image](https://github.com/Labcas-NIST/Labcas-ui/assets/58526347/bad7c349-cdb3-47e9-9fe1-eabd73e9d7c9)

**Comment by hoodriverheather** [comment]
@yuliujpl Please also remove the Institution Bionano and Twinstrand from this, as these are just place holders for MissionBio and Illumina. 

![Image](https://github.com/Labcas-NIST/Labcas-ui/assets/58526347/af20bce1-1df5-4dd5-9c55-20a3bc177923)

**Comment by yuliujpl** [comment]
Hi Heather, sorry what should Bionano and Twinstrand under unblinded should be renamed into instead?

**Comment by hoodriverheather** [comment]
@yuliujpl i think you can just remove. They are place holders and the files are dummy files - correct?
<img width="1359" alt="Screenshot 2023-08-23 at 12 45 11 PM" src="https://github.com/Labcas-NIST/Labcas-ui/assets/58526347/b3f140bc-94b7-4f8a-ae5d-3f4b96b83064">

**Comment by hoodriverheather** [comment]
@yuliujpl - looks great!
