### ISSUE TITLE
Add FileType to File list

### ISSUE THREAD

**Issue by hoodriverheather** [Labcas-NIST/Labcas-ui#72]
Can we add a column in the File view that would allow us to sort or filter based on file extension/type? For example, .xslx, .fastq, .bam, etc.

**Comment by yuliujpl** [comment]
@hoodriverheather is this in the files table within the virtual dataset view? Under "Files in this hierarchy"? I believe currently there's no sorting function there, I will look into adding sorting there if that's what you're referring to!

**Comment by hoodriverheather** [comment]
@yuliujpl I think this was an older request from Sierra. I see you added File type to the Genome Editing and the Cell Line file list, so I think we can close this request. Thanks!
