### ISSUE TITLE
Folder type view at File list level

### ISSUE THREAD

**Issue by hoodriverheather** [Labcas-NIST/Labcas-ui#73]
Create a mock-up based on description below.
From Sierra's doc:
With all of these organizations, would it be possible to introduce a folder type view in the File view of LabCas I guess similar to how we have the hierarchy grouping tree at the collection level but instead drilled down into the file view. I just feel like the file view is a bit overwhelming and takes up a lot of screen space and it muddies what is actually in there. Maybe this is as simple as organizing this view by file type with expandables.

**Comment by yuliujpl** [comment]
@hoodriverheather  if this is still needed, any chance I can get an example of how this looks like? Napkin is fine!

**Comment by yuliujpl** [comment]
I will be implementing the edrn-labcas virtual view into the virtual dataset level

**Comment by hoodriverheather** [comment]
@yuliujpl Looks great and NIST loved it! I'm +1 to push to prod :)
