### ISSUE TITLE
virtual hierarchy level should be sped up (ask Sean how to make it faster)

### ISSUE THREAD

**Issue by yuliujpl** [Labcas-NIST/Labcas-ui#81]

**Comment by yuliujpl** [comment]
@hoodriverheather I think I finally fixed this for flow cytometry and also removed any duplication issues that would occur when you remove or add hierarchies fast. I wonder if you can try bombarding the virtual hierarchy on your end to see if you see any duplicate datasets being created? I'll keep testing on my end to monitor as well!

**Comment by hoodriverheather** [comment]
@yuliujpl It does seem a lot faster. One thing...
When I select Native Hierarchy in the virtual view and then try to click on the "+" to expand any of the datasets, it doesn't work. I just click and get no response.


![Image](https://github.com/Labcas-NIST/Labcas-ui/assets/58526347/ec79a86b-b33e-4336-9bd1-cf69d66e041d)

I will keep trying other virtual hierarchy changes to see if i can get any other strange response.

**Comment by hoodriverheather** [comment]
opened new issue for this bug.
