### ISSUE TITLE
Virtual hierarchy - select native bug

### ISSUE THREAD

**Issue by hoodriverheather** [Labcas-NIST/Labcas-ui#84]
@yuliujpl It does seem a lot faster. One thing...
When I select Native Hierarchy in the virtual view and then try to click on the "+" to expand any of the datasets, it doesn't work. I just click and get no response.

![Image](https://github.com/Labcas-NIST/Labcas-ui/assets/58526347/198f066c-2b81-42db-8d6d-be9eb2b034cf)

**Comment by yuliujpl** [comment]
Hi Heather! It does seem to work, but just slow (takes about 5 seconds for me to load!)

**Comment by hoodriverheather** [comment]
Perfect!
