### ISSUE TITLE
Still seeing Flow Cyt dups in virtual view :(

### ISSUE THREAD

**Issue by yuliujpl** [Labcas-NIST/Labcas-ui#92]
Somehow when playing around with the virtual view I got the duplicate datasets. Here's what I think I did.
See screenshot.

- selected native hierarchy
- expanded the view a few times (clicked on documentation, WG1 i thin)
- selected default
- removed the last facet of the default view (SampleName)
- expanded all and selected a dataset to go into
- clicked back to virtual view
- started removing a lot of the additional default view facets (ExperimentType, ProtocolID and SiteCode)
-**When i remove facets quickly from the default (starting at the end and working backwards) is when this seems to occur. I can recreate it.**

![Image](https://user-images.githubusercontent.com/58526347/256608852-82b563ac-4a04-4fe2-be56-a3a7affa3e34.png)

**Comment by yuliujpl** [comment]
@hoodriverheather  can you try again with and without incognito? Both should be fixed!

**Comment by hoodriverheather** [comment]
It looks great!! YAY!
