### ISSUE TITLE
Flow Cyt Collection Level files not matching

### ISSUE THREAD

**Issue by yuliujpl** [Labcas-NIST/Labcas-ui#94]
The collection level files that are showing below the collection metadata don't match all the files that are listed at the top of the collection. see attached screenshots.

![Image](https://user-images.githubusercontent.com/58526347/256601870-c014c14d-fdfa-4ccc-aa96-7b6cf70171aa.png)

![Image](https://user-images.githubusercontent.com/58526347/256601923-27fb6f63-0741-4a67-9f95-66d9131ce487.png)

**Comment by yuliujpl** [comment]
Removed the files in collection section

**Comment by hoodriverheather** [comment]
Perfect!
