### ISSUE TITLE
error viewing pdf file

### ISSUE THREAD

**Issue by yuliujpl** [Labcas-NIST/Labcas-ui#95]
I'm getting an error when clicking view for pdf files.

![Image](https://user-images.githubusercontent.com/58526347/257339357-fd6c9dfc-96c9-4c38-b05b-31126426b857.png)

**Comment by yuliujpl** [comment]
@hoodriverheather  apologies, which pdf file were you clicking? I clicked on the following and it seems to work for me!
https://ddsa-labcas-staging.jpl.nasa.gov/labcas-ui/f/index.html?file_id=NIST_Flow_Cytometry_Standards_Consortium/NIST_Flow_Cytometry_Standards_Consortium/WG1/sop_wg1_interlab_study.pdf

**Comment by hoodriverheather** [comment]
@yuliujpl All of the flow pdf files are now viewable. Looking at the error message in the screenshot it looks like the one you have in the link above. So yay!! :)

I'm now getting a similar error with the Genome Editing pdfs. Do you want me to open a new issue?

<img width="1379" alt="Screenshot 2023-08-07 at 10 43 00 AM" src="https://github.com/Labcas-NIST/Labcas-ui/assets/58526347/f58b9105-ca71-4dda-bd0d-e533ffeb1a1e">
