### ISSUE TITLE
update cell line collection visualization

### ISSUE THREAD

**Issue by yuliujpl** [Labcas-NIST/Labcas-ui#96]
add a way to show total number of files/expansion
John - want to zoom in and out (timeline as week to year or six month etc.)
For events that occur on the same day, show them on timeline next to each other, not on top of each other.
Link to virtual files associated with event

**Comment by hoodriverheather** [comment]
@yuliujpl I don't see the total number of files per expansion. Also, I'm not sure I'm zooming in and out correctly on my Mac. What key combo should i use? Thanks!

**Comment by yuliujpl** [comment]
@hoodriverheather  apologies, it is a bit confusing. Zooming in/out on the collection level gantt chart is to draw a rectangle! Dataset level is scroll up/down! I know, it's what I get for using different libraries for the different customizations needed :(

**Comment by yuliujpl** [comment]
Ah apologies, the # of files was done for the dataset level already, through those stat icons on the top, let me add this for the collection level!

**Comment by yuliujpl** [comment]
There's a file count in the details table now

**Comment by hoodriverheather** [comment]
@yuliujpl Perfect! Thanks!
