### ISSUE TITLE
Update Cell Line Visualization - Dataset Level

### ISSUE THREAD

**Issue by yuliujpl** [Labcas-NIST/Labcas-ui#97]
![Image](https://user-images.githubusercontent.com/58526347/255708594-fe74abb8-1a77-41a9-981d-32ebfafbb764.png)

Expand height of some of the icons.
Add a way for a user to download the Expansion Unit from the dataset visualization.
Link to virtual files associated with event

**Comment by hoodriverheather** [comment]
This looks great.
